### ISSUE TITLE
Output

### ISSUE THREAD

**Issue by jvoermans** [jerabaul29/LoggerWavesInIce#6]
@jerabaul29 
Could you confirm the parser output for me? Is the MagXYZ, AccXYZ and GyroXYZ the raw data, DCM the rotation matrix and YPR, MagNED and AccNED (North-East-Down) the earth-frame of reference data?
And what are the units of YPR?

**Comment by jerabaul29** [comment]
Hi,

First a small note: these quantities are described in the datasheet if you need more information :) 

https://github.com/jerabaul29/LoggerWavesInIce/blob/master/VN100manual.pdf

Regarding your questions:

- yes, XYZ are raw data in the IMU frame of reference
- yes, DCM is the rotation matrix. I have not used it much though.
- yes, NED is in the Earth-frame of reference. This is usually the data I use myself :)
- YPR is Yaw Pich Roll, these are in degrees, according to the datasheet p. 95/129:

"
Attitude solution as yaw, pitch, and roll in degrees.The yaw, pitch, and roll is given as a 3,2,1 Euler angle rotation sequence describing the orientation of the sensor with respect to the inertial North East Down (NED) **frame
"

Does this answer your questions? Let me know if anything is unclear :) . Were you able to successfully run the code? :) .

**Comment by jvoermans** [comment]
Thanks. Parsing worked perfect, but Windows was doing difficult with the other scripts (some directory problems). I tried to figure it out for a bit, but diverted to Matlab and have rewritten the few lines of code. Get the same results as the spectrum transmitted, so that should be fine :) I'll upload the Matlab file when I'm done.  

One point of confusion, the vertical axis is defined positive downwards, which is corrected to positive upwards in the surface elevation timeseries by the minus-sign in:  elev = -np.real(np.fft.ifft(2 * Yf)) (line 143 of 'look_at_damping.py')? But the timeseries of vertical acceleration are all around -9.81, suggesting that the vertical axis is actually positive upwards?

**Comment by jerabaul29** [comment]
This is great to hear! :)

Yes, I expect this does not work well on windows. The reason is that I only develop on linux, and I do not care of using the 'right' method for paths (which is also quite a bit longer to write), for example using ```os.path.join(base_path, file)```, instead I usually write the much shorter ```base_path + "/" + file```, which is fine on linux, as ```/``` is the file delimiter there, but not on windows, which uses ```\``` usually as a path delimiter. Consider running on either linux, or use the linux subsystem for windows in some folders using the unix convention for path delimiters, if this is possible to do (not an expert on that :) ).

That sounds good. I prefer python myself of course, but if you want to provide some matlab stuff, and want to push it to the repo, that may be great to other users :) Feel free to clone / create a feature branch / create a pull request (if you are not familiar with the workflow, feel free to google and / or open an issue asking for some help here :) ).

Mmh, indeed this is always confusing, and difficult to debug, as obtaining +elevation or -elevation (if there is a sign mistake) has no influence on the spectra, SWH, Tp etc... I think that: 1) orientation is indeed upwards, 2) we are interested in the wave acceleration, which is the opposite of the acceleration felt by the sensor.

It is actually always a bit tricky (I had a lot of headaches getting it to work there for example, same issue for rotation :) ): https://github.com/jerabaul29/IntegrateGyroData . Basically the idea is that if the IMU feels an acceleration -A, depending on the conventions used, that are dependent on the chip, that may mean that the object is accelerating in the direction +A. Think about it this way: if the X axis is upwards, and gravity is reported as -9.81, then accelerating upwards with make you feel like "stronger gravity", i.e. more negative vertical acceleration, for example -12.81, i.e. the IMU "feels" an additional acceleration of -3, but really the object is accelerating upwards. That may mean that converting from IMU acceleration feeling to object acceleration in the coordinate system, you need to have some - signs here and there. Does that make sense / is that clear? :)

**Comment by jvoermans** [comment]
Thanks, I think I understand it now
